version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "transcribe-comprehend-pipeline"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-xk4xlepaab6i"
s3_prefix = "transcribe-comprehend-pipeline"
region = "eu-west-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
